# Generated by Django 4.2.1 on 2023-06-09 18:39

from django.db import migrations, models
import django.db.models.deletion
import user_access.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDefinition',
            fields=[
                ('ip_address', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=50)),
                ('server_ad_grp', models.CharField(max_length=50)),
                ('server_key', models.CharField(max_length=50)),
                ('is_pci', models.CharField(max_length=5)),
                ('is_infra', models.CharField(max_length=5)),
                ('is_db', models.CharField(max_length=5)),
                ('is_managed_ad', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserDefinition',
            fields=[
                ('emp_user_id', models.CharField(default='abc', max_length=50, primary_key=True, serialize=False)),
                ('emp_reporting_manager', models.CharField(max_length=50)),
                ('initial_ad_grps', models.TextField(null=True)),
                ('servers', models.TextField(null=True)),
                ('jenkins_job', models.TextField(null=True)),
                ('databags', models.TextField(null=True)),
                ('database', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessDefinition',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_details', models.TextField()),
                ('access_type', models.CharField(default='Test', max_length=50)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approver_mail', models.CharField(editable=False, max_length=50)),
                ('approval_date', models.DateTimeField(auto_now=True)),
                ('manager_approval', models.CharField(default='Pending', max_length=50)),
                ('access_granted', models.CharField(default='Pending', max_length=50)),
                ('emp_user_id', user_access.models.VarCharForeignKey(default='abc', on_delete=django.db.models.deletion.DO_NOTHING, to='user_access.userdefinition')),
            ],
        ),
    ]
