# Generated by Django 4.2.1 on 2023-06-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefinition',
            name='emp_display_name',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
