# Generated by Django 4.2.1 on 2023-06-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_access', '0002_userdefinition_emp_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdefinition',
            name='emp_display_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
